name: Sync with Template

on:
  workflow_dispatch:
  schedule:
    # Führt den Workflow jeden Montag um 06:00 Uhr aus
    - cron: "0 6 * * 1"

jobs:
  call-sync:
    uses: Wamocon/github_workflow/.github/workflows/template-sync.yml@main
    with:
      # Passe den Namen an, falls dein Template anders heißt
      source_repo: "Wamocon/temp-1"
    secrets: inherit