name: Deploy to Vercel (Preview)

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: Wamocon/github_workflow/.github/workflows/deploy-preview.yml@main
    with:
      vercel_env: preview
    secrets: inherit
