name: Reusable Template Sync

on:
  workflow_call:
    inputs:
      source_repo:
        description: "Quell-Template-Repository"
        required: true
        type: string
    secrets:
      ORG_PAT:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ORG_PAT }}

      - name: Sync from Template
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_gh_token: ${{ secrets.ORG_PAT }}
          target_gh_token: ${{ secrets.ORG_PAT }}
          source_repo_path: ${{ inputs.source_repo }}
          upstream_branch: main
          pr_title: "chore: Sync Upstream Template Updates"
          pr_commit_msg: "chore: Merge Template Updates"
          is_force_deletion: "true"